#Data Master PLC
#Fri Sep 04 23:50:49 WIB 2026
global.interval=1
plc.1.category=PAINT SHOP
plc.1.ip=10.98.192.10
plc.1.name=PLC MES EMS
plc.10.category=PAINT SHOP
plc.10.ip=10.98.193.10
plc.10.name=PLC DI Water CPU
plc.11.category=PAINT SHOP
plc.11.ip=10.98.193.50
plc.11.name=PLC Phosphate
plc.12.category=PAINT SHOP
plc.12.ip=10.98.193.60
plc.12.name=PLC Boiler
plc.13.category=PAINT SHOP
plc.13.ip=10.98.193.81
plc.13.name=PLC Chiller Main
plc.14.category=PAINT SHOP
plc.14.ip=10.98.193.165
plc.14.name=PLC Chiller ED
plc.15.category=PAINT SHOP
plc.15.ip=10.98.193.180
plc.15.name=PLC Chiller 1
plc.16.category=PAINT SHOP
plc.16.ip=10.98.193.195
plc.16.name=PLC Chiller 2
plc.17.category=PAINT SHOP
plc.17.ip=10.98.193.210
plc.17.name=PLC Chiller 3
plc.18.category=PAINT SHOP
plc.18.ip=10.98.193.225
plc.18.name=PLC Wastewater
plc.19.category=PAINT SHOP
plc.19.ip=10.98.194.180
plc.19.name=PLC Robot
plc.2.category=PAINT SHOP
plc.2.ip=10.98.194.25
plc.2.name=PLC MES Conveyor MCP
plc.20.category=PAINT SHOP
plc.20.ip=10.98.194.220
plc.20.name=PLC Paint Mixing
plc.21.category=BODY SHOP
plc.21.ip=10.98.128.21
plc.21.name=PLC UB1 Line
plc.22.category=BODY SHOP
plc.22.ip=10.98.129.21
plc.22.name=PLC Main Line 1
plc.23.category=BODY SHOP
plc.23.ip=10.98.130.21
plc.23.name=PLC Main Line 2
plc.24.category=BODY SHOP
plc.24.ip=10.98.131.21
plc.24.name=PLC Metal Finish
plc.25.category=GA SHOP
plc.25.ip=10.98.160.11
plc.25.name=PLC Trim Line
plc.26.category=GA SHOP
plc.26.ip=10.98.161.11
plc.26.name=PLC Chasis 2
plc.27.category=GA SHOP
plc.27.ip=10.98.161.12
plc.27.name=PLC AGV
plc.28.category=GA SHOP
plc.28.ip=10.98.163.11
plc.28.name=PLC Final
plc.29.category=GA SHOP
plc.29.ip=10.98.164.11
plc.29.name=PLC Filling
plc.3.category=PAINT SHOP
plc.3.ip=10.98.195.11
plc.3.name=PLC RCP 03
plc.30.category=GA SHOP
plc.30.ip=10.98.164.12
plc.30.name=PLC Filling 2
plc.31.category=GA SHOP
plc.31.ip=10.98.162.11
plc.31.name=PLC Subline
plc.32.category=GA SHOP
plc.32.ip=10.98.164.13
plc.32.name=PLC Filling PM
plc.33.category=GA SHOP
plc.33.ip=10.98.160.13
plc.33.name=PLC Trim 1
plc.34.category=GA SHOP
plc.34.ip=10.98.160.12
plc.34.name=PLC PBS
plc.35.category=GA SHOP
plc.35.ip=10.98.163.12
plc.35.name=PLC Door
plc.4.category=PAINT SHOP
plc.4.ip=10.98.195.120
plc.4.name=PLC RCP 05
plc.5.category=PAINT SHOP
plc.5.ip=10.98.197.50
plc.5.name=PLC Plastic Part MCP
plc.6.category=PAINT SHOP
plc.6.ip=10.98.192.71
plc.6.name=PLC PT ED
plc.7.category=PAINT SHOP
plc.7.ip=10.98.192.111
plc.7.name=PLC DC Power
plc.8.category=PAINT SHOP
plc.8.ip=10.98.192.131
plc.8.name=PLC UF System
plc.9.category=PAINT SHOP
plc.9.ip=10.98.192.151
plc.9.name=PLC MES ED Oven
