#Konfigurasi Database Aplikasi
#Sat Aug 29 00:19:24 WIB 2026
db.driver=org.postgresql.Driver
db.host=localhost
db.name=app
db.password=admin
db.port=5432
db.type=PostgreSQL
db.url=jdbc\:postgresql\://localhost\:5432/app
db.username=postgres
