#Konfigurasi Aplikasi
#Sat Aug 29 04:31:28 WIB 2026
db.driver=org.postgresql.Driver
db.host=localhost
db.name=app
db.password=admin
db.port=5432
db.type=PostgreSQL
db.url=jdbc\:postgresql\://localhost\:5432/app
db.username=postgres
ui.default_menu=Monitor
ui.height=650
ui.language=Bahasa Indonesia
ui.width=1050
