#DC Tool Configuration
#Sun Aug 30 04:59:25 WIB 2026
dctool.1.category=Line 1
dctool.1.ip=192.168.1.101
dctool.1.name=DC Tool Front Axle
dctool.2.category=Line 1
dctool.2.ip=192.168.1.102
dctool.2.name=DC Tool Rear Axle
dctool.3.category=Line 2
dctool.3.ip=192.168.1.103
dctool.3.name=DC Tool Engine Mount
dctool.4.category=GA
dctool.4.ip=10.98.98.122
dctool.4.name=Tightening
