# Data MES PC (Monitor Module)
# Format: pc.[id].category, pc.[id].name, pc.[id].ip

# PAINT SHOP
pc.1.category=PAINT SHOP
pc.1.name=PC Operator Paint 1
pc.1.ip=10.98.200.11

pc.2.category=PAINT SHOP
pc.2.name=PC Operator Paint 2
pc.2.ip=10.98.200.12

# BODY SHOP
pc.3.category=BODY SHOP
pc.3.name=PC Quality Control Body
pc.3.ip=10.98.140.50

# GA SHOP
pc.4.category=GA SHOP
pc.4.name=PC Final Line GA
pc.4.ip=10.98.170.21
